[tools]
go = "latest"
golangci-lint = "latest"
goreleaser = "latest"
kube-controller-tools = "latest"

[tasks.generate]
description = "Generate DeepCopy methods for API objects"
run = "controller-gen object:headerFile=hack/boilerplate.go.txt paths=./apis/..."
